sudo: required # use Travis Trusty env (http://docs.travis-ci.com/user/ci-environment/)
dist: trusty
language: generic # PHP is not available in "mega" image, so we use "minimal" image and setup runtimes separately

before_install:
# Install execution environment (php, phpunit, mysql, composer)
  - sudo apt-get update
  - sudo apt-get install php5 php5-gd php5-mcrypt php5-curl php5-intl php5-xsl php5-mysql
  - sudo php5enmod mcrypt
  - sudo apt-get install phpunit
  - sudo apt-get install mysql-client-core-5.6 mysql-client-5.6 mysql-server-5.6
  - sudo php -r "readfile('https://getcomposer.org/installer');" | sudo php -- --install-dir=/usr/local/bin --filename=composer
  - sudo apt-get remove php5-xdebug # to prevent composer warning See https://getcomposer.org/xdebug
# Display versions for tools
  - php --version
  - phpunit --version
  - composer --version
  - git --version
# Get auth keys: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html
  - composer config -g http-basic.repo.magento.com $M2_KEY_PUB $M2_KEY_PRIV
# Copy Travis CI configuration from template and deploy Magento 2 application
  - pwd # control current path ('LOCAL_ROOT' in templates.json)
  - cp deploy_cfg.sh.travis deploy_cfg.sh # create configuration for Travis from template
  - sh deploy.sh

#
script:
  - php ./work/vendor/bin/phpunit -c work/vendor/flancer32/mage2_ext_login_as/test/unit/phpunit.dist.xml
  - php ./work/vendor/bin/phpunit -c work/vendor/flancer32/mage2_ext_login_as/test/functional/phpunit.dist.xml
#  - php ./work/vendor/bin/phpunit - ./work/dev/tests/unit/phpunit.xml.dist # run Magento 2 unit tests

notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: change # [always|never|change], default: change
    on_failure: change # [always|never|change], default: change